name: PR Check

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: read

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Run unit tests
        run: mvn -B -f lna-session-api/pom.xml test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}